always_on_subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.0
always_show_subgrid: false
app_version: 0.2.1
background_rgba:
- 0.0
- 0.0
- 0.0
- 0.1
classname: AppConfig
font_size_multiplier: 0.6
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 26
  num_cells_y: 1
- border_width: 1.75
  callback: build_cell_strings
  num_cells_x: 1
  num_cells_y: 26
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1
grid_rgba:
- 1.0
- 1.0
- 1.0
- 0.7
hide_cursor_on_click: false
hide_location: bottom_left
keymap:
  close dialog: ":"
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: null
  execute mouse action: Space
  hide overlay: Escape
  hold for drag: null
  hold for move: null
  hold for right button: Command
  release hold/drag: null
  repeat last mouse action: null
  show overlay: cmd+alt+shift+ctrl+Space tap
  switch monitor left: 1 tap
  switch monitor right: 2 tap
  toggle overlay: null
monitor_assignments: auto
mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
move_duration_ms: 100
move_real_cursor_with_virtual: false
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
- 8
- 3
subgrid_font_size_multiplier: 0.65
subgrid_mouse_action_keys: QWFPLUY;ARSTNEIOZXCDKH,.
subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.0
subgrid_text_rgba:
- 1.0
- 0.0
- 0.0
- 0.8
tap_threshold_ms: 200
text_rgba:
- 0.0
- 0.7
- 0.2
- 1.0
window_opacity: 1.0
