[metadata]
name = "zsh-history"
description = "A channel to select from your zsh history"
requirements = ["zsh"]

[source]
command = "if command -v tac >/dev/null 2>&1; then tac ${HISTFILE:-${HOME}/.zsh_history}; else tail -r ${HISTFILE:-${HOME}/.zsh_history}; fi"
display = "{split:;:1..}"
output = "{split:;:1..}"
no_sort = true
frecency = false

[keybindings]
ctrl-e = "confirm_selection"

[actions.execute]
description = "Execute the selected command"
command = "zsh -c '{split:;:1..}'"
mode = "execute"
