# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_commit\
$aws\
$hostname\
$time\
$cmd_duration\
$line_break\
$status\
$character"""

# Move the directory to the second line
palette = 'gruvbox-material'

[palettes.gruvbox-material]
# background
bg_dim = '#141617'
bg0 = '#1D2021'
bg1 = '#282828'
bg3 = '#3C3836'
# middleground
grey0 = '#7C6F64'
grey1 = '#928374'
# foreground
fgO = '#D4BE98'
fg1 = '#DDC7A1'
# normal colors
red = '#EA696A'
green = '#A9B665'
yellow = '#D8A657'
blue = '#7DAEA3'
purple = '#D3869B'
aqua = '#89B482'
orange = '#E78A4E'
# dim colors
bg_red = '#EA6962'
bg_green = '#A9B665'
bg_yellow = '#D8A657'
bg_blue = '#659F92'
bg_purple = '#C86580'
bg_aqua = '#6BA163'
bg_orange = '#E16F23'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[hostname]
ssh_only = true
format = "[$hostname](bold fg:purple) "
trim_at = "."
disabled = false

[git_commit]
tag_symbol = " tag "

[git_status]
style = "grey1"

[git_branch]
format = "[$branch ]($style)"
style = "grey1"

[aws]
symbol = "aws "
style = "orange"

[directory]
style = "blue"
read_only_style = 'fg:orange'
read_only = " "

[status]
symbol = "[x](bold red) "

[time]
disabled = false

