import = [
    # "~/.config/alacritty/themes/themes/zenburn.toml"
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.columns = 150
dimensions.lines = 40


decorations = "Buttonless"

opacity = 0.94
blur = false

option_as_alt = "both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16

#for video
# size = 35.0
